on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@cf871b8ccef867874d90a271812017f4648a9406
        with:
          token: doot
          # branch: ${{ github.ref }}
