on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@48d66c8f813ae0a887a3725746e0ecf3b3798da6
        with:
          token: doot
          # branch: ${{ github.ref }}
