on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@643ca75b0c834e1a7be1fcf2ec10e85c8876984e
        with:
          token: doot
          # branch: ${{ github.ref }}
