on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@2614212ff598b9c92052d957ccb324627b52ab1c
        with:
          token: doot
          # branch: ${{ github.ref }}
