on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@5705fff020cc766633f7d6e467f4512564843330
        with:
          token: doot
          # branch: ${{ github.ref }}
