on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@281f33ae993e852f70f6faa17e00171e943799d3
        with:
          token: doot
          # branch: ${{ github.ref }}
