on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@43bff25dceb64365f00fe6d7bd3d131deed266be
        with:
          token: doot
          # branch: ${{ github.ref }}
