on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@39452339febf2226faeca94c5bb9a995c68d8dd6
        with:
          token: doot
          # branch: ${{ github.ref }}
