on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@dd31a7ce5820c94cfe6538e43190281d76116dc0
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          # branch: ${{ github.ref }}
