on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: EccentricVamp/screeps-action@d15807d7b47d2d138a1ff6c4f3415bc95635b2e3
        with:
          token: ${{ secrets.AUTH_TOKEN }}
