on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@5d15e0fe48683a18cd741f2f2d2b5d88b766d3a1
        with:
          token: doot
          # branch: ${{ github.ref }}
