on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@63983e995b1b4e7098b32ca63e642191d53e965b
        with:
          token: doot
          # branch: ${{ github.ref }}
