on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@2d284eb5d03df7de61d22a01bbd371a94bd3d996
        with:
          token: doot
          # branch: ${{ github.ref }}
