on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: EccentricVamp/screeps-action@437fc88ea32a32ff6c1bb531870a8dfbe9db2fdc
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          # branch: ${{ github.ref }}
