on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EccentricVamp/screeps-action@d69f0777a9949005606cc5f8c7c1165df7d91c1f
        with:
          token: doot
          # branch: ${{ github.ref }}
