on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: EccentricVamp/screeps-action@v0.1.1
        with:
          token: ${{ secrets.AUTH_TOKEN }}
      - shell: bash
        env:
          TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo $TOKEN:0:5
          echo $TOKEN:5
